spring:
    datasource:
        url: jdbc:postgresql://${DATABASE_URL:localhost:5432/tomcaching}
        username: ${DATABASE_USERNAME:tomcaching}
        password: ${DATABASE_PASSWORD:tomcaching}
        driver-class-name: org.postgresql.Driver

    liquibase:
        url: ${spring.datasource.url}
        user: ${spring.datasource.username}
        password: ${spring.datasource.password}
        driver-class-name: ${spring.datasource.driver-class-name}
        database-change-log-table: liquibase_changelog
        database-change-log-lock-table: liquibase_changelog_lock
        change-log: classpath*:/changelog.sql
        clear-checksums: true

server:
    port: ${PORT:8080}
    error:
        include-exception: false
        include-stacktrace: never
        include-message: never
        include-binding-errors: always

admin:
    password: ${ADMIN_PASSWORD:development-admin-password}