--liquibase formatted sql

--changeset jirkavrba:create-caches-table
create table caches
(
    id                         int              not null generated by default as identity primary key,
    cache_type                 varchar(32)      not null,
    cache_title                varchar(512)     not null,
    cache_content              varchar(4096)    not null,
    cache_found                boolean default false,
    cache_locked               boolean default false,
    cache_question             varchar(4096)    null,
    cache_solution             varchar(32)      null,
    coordinates_latitude       double precision not null,
    coordinates_longitude      double precision not null,
    fake_coordinates_latitude  double precision null,
    fake_coordinates_longitude double precision null
);

--changeset jirkavrba:add-hints-to-caches
alter table caches
    add column cache_hint varchar(4096) not null default '';

--changeset jirkavrba:add-challenge-urls-to-caches
alter table caches
    add column challenge_url varchar(128) null;